### ISSUE TITLE
منبع تغذیه سوییچینگ متغیر

### ISSUE THREAD

**Issue by omid-mazarei** [aKaReZa75/PCB#1]
سلام و عرض ارادت خالصانه
سوال من درباره آموزش رگولاتور متغیر سوییچینگ (adjustable voltage Regulator) است ،با توجه به این ویدیو ظاهرا اینکه ما از ایسی رگولاتور متغیر استفاده کنیم نمی توانیم در ورودی و در خروجی ولتاژ متغیر (البته متغیر در دامنه ذکر شده در کاتالوگ) داشته باشیم یعنی نمی توانیم با یک المان متغیر کننده(مقاومت متغیر شبکه فیدبک) نمی توان یک منبع متغیر ولتاژ ساخت چون به ازای هر ولتاژ ورودی و خروجی مشخص همه المانهای دیگر مدار مثل خازنها و سلف هم باید تغییر کند،البته همانطور که مطلعید ماژولهایی در بازار با همین ای سی های سوییچینگ موجود در آموزش ، وجود دارد که با یک یا دو مقاومت متغیر ولتاژ و حتی جریان خروجی را می توان بدلخواه تنظیم نمود و در مورد ورودی هم در "دامنه مجاز"می توان به این ماژولها ولتاژ اعمال کرد ولی برداشت من از این آموزش این بود که با وجود متغیر بودن ای سی ها به ازای هر ولتاژ ورودی و خروجی مطلوب بقیه المانها مثل خازنها و سلف و... باید محاسبه و تغییر کند و این ماژولهای متغیر موجود در بازار هم استاندارد نیستند.
من از قبل یک ایسی کمتر شناخته شده رگولاتور سوییچینگ داشتم که می خواستم با این ای سی یک منبع ولتاژ متغیر و دقیق آزمایشگاهی کوچک درست کنم که ظاهرا کار استانداردی به دلایلی که بالا ذکر کردم نیست،این ای سی با توجه به دیتا شیت پیوست باید کارایی خوبی داشته باشد ولی با توجه به شماتیک پیشنهادی در دیتا شیت و همچنین آموزش شما امکان متغیر کردن بصورت استاندارد وجود ندارد.
ممنون میشم در این زمینه راهنمایی بفرمایید.با تشکر
[fp6102v092-lf.pdf](https://github.com/user-attachments/files/16852412/fp6102v092-lf.pdf)

**Comment by aKaReZa75** [comment]
سلام و عرض ادب، اتفاقا میشه، کافیه که از یک مولتی ترن بجای یکی از مقاومت های قیدبک استفاده کنید ( باید اون مقاومتی رو مولتی ترن بجاش قرار بدین که فرمول نهایی رفتار خطی داشته باشه) و بعد اون همه محاسبات رو برای بدترین حالت ( که خروجی بیشترین ولتاژ باشه و ورودی روی کمترین) انجام بدین، با این کار مشکلی نخواهید داشت.
این مدل آیسی که فرستادین کار کردن باهاش سخت میشه و طراحی مدار اون، چونکه جبرانساز اونرو باید خودتون طراحی کنید که کار ساده ای نیست درکل.
اما رگولاتوریم که دارید کاهنده هست این موضوع رو هم مدنظر داشته باشید، موفق باشید.

**Comment by omid-mazarei** [comment]
سلام مجدد،این جبران ساز چیه استاد؟تو این ای سی که من دارم طراحی خاصی داره یا تو همه رگولاتور های متغیر؟اگه امکانش هست یه منبع معرفی کنید که مطالعه کنم،ممنون

**Comment by aKaReZa75** [comment]
توی همه رگولاتور ها هست، بعضیاشون داخلی هست و بعضیاشون بیرون کشیده شده که خود طراح، مقادیرشو باتوجه به نیازش طراحی کنی.
جیران ساز مربوط به کنترل حلقه بسته هست و زمانی که کنترل حلقه بسته میشه، برای اینکه خروجی سیستم ما، به اون مقدار مطلوب و تعیین شده برسه از جبران ساز استفاده میکنند، حالا اگه این جبران ساز درست طراحی نشه، سیستم ممکنه ناپایدار بشه، یا اینکه سیستم خیلی کند به اون مقدار مشخص شده برسه، یا اینکه به صورت نوسانی به اون مقدار برسه و یا اینکه در مطلوب ترین حالت ما، در کوتاه ترین زمان، با کمترین تغییرات و نوسان به اون مقدار برسه!
کهدر اینجا سیستم ما همین رگولاتور هست و مقدار مطلوب هم ولتاژ خروجی مدنظر ما از رگولاتور هست.
برای اطلاعات بیشتر میتونید جبران ساز های PID رو مطالعه کنید.

**Comment by omid-mazarei** [comment]
سلام استاد من دیشب کمی مطالعه کردم بعد هم جواب شما رو که دیدم و بعد PID هم سرچ کردم این شعر حافظ شد حال و روز من:
از هر طرف که رفتم، جز وحشتم نَیَفزود  / زِنهار از این بیابان، وین راهِ بی‌نهایت
واقعا دیگه دارم وحشت میکنم هر قسمتی رو که میخوام یه کوچولو وارد بشم تازه واردِ دنیایی دیگه میشم کاملا نا شناخته و غیر منتظره،دارم پشیمون میشم از وادی که پا گذاشتم خیلی وحشتناکه 
این وصف حالم بود بعد از مطالعه مقوله فیدبک وجبران سازی و جبران سازی فرکانسی و.... که من فکر می کردم ساده است و لی خودش دنیاییه،نمی دونم شاید واقعا دیگه ادامه ندم اما در این دیتا شیت که براتون فرستادم یه شماتیک در آخرش داره که با توجه به چیزهایی که شما فرمودین و مطالعه **دیشب تا حالای** من باید همون مدار جبران ساز باشه ،**عکسشو اینجا دوباره میزارم** ممنون میشم بفرمایید همین برا ولتاژ متغیر هم کار مبکنه یا برا ولتاژ متغیر فعلا کار میکنه یا نه ،البته رگولاتوهای موجود در ویدیوی آموزشی هم تهیه می کنم ،اینکه رو این ای سی میخوام کار کنم چند علت داره اونم اینکه اولین طراحی است که قراره اجرا بشه،مدار چاپی رو برا اولین بار خودم میخوام چاپ کنم(البته درسنین نو جوانی 30-35 سال پیش با لتراست یکبار انجام دادم ولی اولیش هست که با این سیستم نور دهی UVو وسایل و مراحل جانبی که خیلی وقته تهیه کردم انجام بدم) من هنوز جرائت نکردم ای سی SMD به این کوچکی رو لحیم کنم اینم مهمه برام تو این پروژه،من متاسفانه چون راه رو شاید از ایتدا اشتباه رفتم و خودم رو درگیر چاپ PCB کردم و وسایل و مواد به نسبت زیادیگرفتم و هنوز استفاده نکردم و لا اقل از بابت ئتوری روی ساخت PCB که دو رو باشه ،وایا هاش درست متالیزه بشه،قلع اندود شمیایی بشه حیفه اینو اینجا رها کنم لا اقل اینو تجربه کنم،به هر حال یه لطف کنید تو این شکل نگاه کنید ببنید مدار جبران ساز برای متغیر کردن این ای سی همین مقاومت وخازن درسته و کافیه یا نه،با تشگر و عرض ارادت قلبی
![image](https://github.com/user-attachments/assets/54b51a98-a18f-4367-b7da-e23f87de7072)


البته این قسمتش هم هست
![image](https://github.com/user-attachments/assets/611d6b7c-d7ef-4084-b81c-f4c2a8b11d9e)

**Comment by aKaReZa75** [comment]
نه دوست من، جا نزید!
محبث جبران ساز کلا محث سنگین و سختیه، که مربوط به گرایش کنترل میشه و خودش چندین واحد تخصصی داره که باید پاس بشه! و به طبع با یک مطالعه جزئی نمیشه بهش مسلط شد! خود من که رشته تحصلیم بوده باز کلی سوال و ابهام برای هست توی طراحی یک کنترل کننده مناسب و همیشه چالش های زیادی داره این معقوله!
برای همین موضوع بود که من از آیسی هایی استفاده کرد که نیاز به جبران ساز خارجی نداشته باشه!
حالا انشالله توی دوره پاور الکترونیک زمانی که جبران ساز طراحی میکنیم میبینید و متوجه میشید که برای مشخص کردن مقدار همون خازن و مقاومت بالای 1 ساعت باید محاصبه کنیم و نمودار رسم کنیم!
در خصوص بخش دوم که میفرمایید از مقادیر جبران ساز رو چک کنم، حقیقیتش مقدار عددی رو نمیتونم بررسی کنم و نظری بدم چونکه هیچ دیدی نسبت بهش ندارم و کار هم نکردم با این آیسی که بخوام نظری بدم که مفید باشه! 
ولی اگه پیشنهاد خود دیتاشیت هست پس حتما معتبر هست.
مورد بعدی هم اینکه من جبران ساز PID رو بهتون معرفی کردم که صرفا با مفاهیمش آشنا بشید که اصلا جبران ساز چیه و چه کاری میکنه، اما ایم جبران سازی که استفاده شده اینجا اصلا PID نیست، که برای اینکه بیشتر سردرگم نشید، دنبالش رو نگیرید بهتره، اجازه بدید با آموزش های کانال پیش بریم که بیشتر جبران سازهای کاربردی رو یاد میگیریم و طراحی هم میکنیم.
پیشنهاد من به شما اینهکه برای اینکه بجث جبران ساز و کاربردشون رو بهتر متوجه بشید کلیپ زیر رو تماشا کنید و در نهایت از آیسی های مثل 2596 استفاده کنید برای کاربرد مد نظرتون که هم SMD هست، هم پایه های اون کوچیک نیست و هم جبران ساز خارجی نیاز نداره و همین اینکه توی کانال المان های اون رو طراحی کردیم!
https://www.youtube.com/watch?v=JFTJ2SS4xyA
